INSERT INTO USER (USER_ID,LOGIN,FIRST_NAME,LAST_NAME,EMAIL,PHONE,IS_ADMIN,IS_DELETED) VALUES(1,'limin','Min','Li','limin.hust@foxmail.com','18621717879','Y','N');
INSERT INTO USER (USER_ID,LOGIN,FIRST_NAME,LAST_NAME,EMAIL,PHONE,IS_ADMIN,IS_DELETED) VALUES(2,'shenxiaoying','Xiaoying','Shen','ada.shen@foxmail.com','15000581925','N','N');

INSERT INTO AFFILIATE (AFFILIATE_ID,NAME, ADDRESS) VALUES (1,'Emperor CrossFit','255, Lanhua Rd, Pudong,Shanghai');
INSERT INTO AFFILIATE (AFFILIATE_ID,NAME, ADDRESS) VALUES (2,'Stud CrossFit', 'i dont know address');


INSERT INTO OWN_AFFILIATE VALUES(1,1);
INSERT INTO OWN_AFFILIATE VALUES(1,2);


INSERT INTO PUBLISHED_WORKOUT (PUBLISHED_WORKOUT_ID,NAME,TYPE,PUBLISHED_BY,PUBLISHED_DATE,WORKOUT_DETAILS,RX_VERSION,SCALE_VERSION1,SCALE_VERSION2,IS_BENCHMARK,IS_DELETED,COMMENT)
VALUES(1,'5k run','FORTIME',1,'2017-12-16','Run 5k for time','Run 5k for time','','','Y','N','nothing to comment');

INSERT INTO PUBLISHED_WORKOUT (PUBLISHED_WORKOUT_ID,NAME,TYPE,PUBLISHED_BY,PUBLISHED_DATE,WORKOUT_DETAILS,RX_VERSION,SCALE_VERSION1,SCALE_VERSION2,IS_BENCHMARK,IS_DELETED,COMMENT)
VALUES(2,'500m row','FORTIME',1,'2017-12-16','Row 500m for time','Row 500m for time','','','Y','N','nothing to comment');

INSERT INTO MOVEMENT VALUES(1,'Run','ENDUR');
INSERT INTO MOVEMENT VALUES(2,'Row','ENDUR');
INSERT INTO MOVEMENT VALUES(3,'Back Squat','WEIGHT');
INSERT INTO MOVEMENT VALUES(4,'Front Squat','WEIGHT');

INSERT INTO LOGGED_WORKOUT VALUES(1,1,1,'2017-12-17','00:25:00','PT25M',0,0,0,'feels good');
INSERT INTO LOGGED_WORKOUT VALUES(2,1,1,'2017-12-18','00:24:30','PT24M30S',0,0,0,'feels strong');
