CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  LOGIN CHAR(16) UNIQUE NOT NULL,
  PASSWORD CHAR(100),
  FIRST_NAME VARCHAR(16),
  LAST_NAME VARCHAR(16),
  EMAIL VARCHAR(50),
  PHONE CHAR(20),
  IS_ADMIN CHAR(1),
  IS_DELETED CHAR(1)
);

CREATE TABLE AFFILIATE (
    AFFILIATE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL
);

CREATE TABLE OWN_AFFILIATE(
    AFFILIATE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL
);
ALTER TABLE OWN_AFFILIATE ADD PRIMARY KEY (USER_ID, AFFILIATE_ID);
ALTER TABLE OWN_AFFILIATE ADD FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);
ALTER TABLE OWN_AFFILIATE ADD FOREIGN KEY (AFFILIATE_ID) REFERENCES AFFILIATE(AFFILIATE_ID);


CREATE TABLE JOIN_AFFILIATE(
    USER_ID BIGINT NOT NULL,
    AFFILIATE_ID BIGINT NOT NULL
);

ALTER TABLE JOIN_AFFILIATE ADD PRIMARY KEY (USER_ID, AFFILIATE_ID);
ALTER TABLE JOIN_AFFILIATE ADD FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);
ALTER TABLE JOIN_AFFILIATE ADD FOREIGN KEY (AFFILIATE_ID) REFERENCES AFFILIATE(AFFILIATE_ID);



CREATE TABLE PUBLISHED_WORKOUT(
    PUBLISHED_WORKOUT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    TYPE VARCHAR(20),
    PUBLISHED_BY BIGINT NOT NULL,
    PUBLISHED_DATE DATE NOT NULL,
    WORKOUT_DETAILS VARCHAR(500) NOT NULL,
    RX_VERSION VARCHAR(500) NOT NULL,
    SCALE_VERSION1 VARCHAR(500),
    SCALE_VERSION2 VARCHAR(500),
    IS_BENCHMARK CHAR(1),
    IS_DELETED CHAR(1),
    COMMENT VARCHAR(1024)
);
ALTER TABLE PUBLISHED_WORKOUT ADD FOREIGN KEY (PUBLISHED_BY) REFERENCES USER(USER_ID);

CREATE TABLE MOVEMENT(
    MOVEMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR (20),
    TYPE VARCHAR (25)
);

CREATE TABLE LOGGED_WORKOUT(
    LOGGED_WORKOUT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PUBLISHED_WORKOUT_ID BIGINT NOT NULL,
    LOGGED_BY BIGINT NOT NULL,
    LOGGED_DATE DATE NOT NULL,
    RESULTS VARCHAR(1000) NOT NULL,
    DURATION VARCHAR(20),
    TOTAL_REPS INT,
    SETS INT,
    REPS INT,
    COMMENTS VARCHAR(1024)
);
ALTER TABLE LOGGED_WORKOUT ADD FOREIGN KEY (PUBLISHED_WORKOUT_ID) REFERENCES PUBLISHED_WORKOUT(PUBLISHED_WORKOUT_ID);
ALTER TABLE LOGGED_WORKOUT ADD FOREIGN KEY (LOGGED_BY) REFERENCES USER(USER_ID);

